# Basit, genel amaçlı 0.4 mm nozül / 1.75 mm PLA profili.
layer_height = 0.2
first_layer_height = 0.2
nozzle_diameter = 0.4
filament_diameter = 1.75
temperature = 210
first_layer_temperature = 215
bed_temperature = 60
first_layer_bed_temperature = 60
perimeters = 2
top_solid_layers = 4
bottom_solid_layers = 4
fill_density = 15%
fill_pattern = grid
print_speed = 50
travel_speed = 130
filament_density = 1.24
filament_cost = 20
gcode_flavor = marlin2
use_relative_e_distances = 1
start_gcode = G28 ; home all axes\nG92 E0
end_gcode = M104 S0\nM140 S0\nM84
